### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by shanyuejun** [hyunkoome/CenterPointPillar#3]
Can you provide checkpoint_epoch_24.pth

**Comment by hyunkoome** [comment]
> Can you provide checkpoint_epoch_24.pth

Hi @shanyuejun 
Could you let me know your email address? I will let you know how you get it.

**Comment by shanyuejun** [comment]
> > Can you provide checkpoint_epoch_24.pth
> 
> Hi @shanyuejun Could you let me know your email address? I will let you know how you get it.

2644349265@qq.com Thank you

**Comment by jessieWu3** [comment]
> > Can you provide checkpoint_epoch_24.pth
> 
> Hi [@shanyuejun](https://github.com/shanyuejun) Could you let me know your email address? I will let you know how you get it.

Hi！Can you send me  checkpoint_epoch_24.pth? My email address : 374067074@qq.com
Thanks a lot!
